jobs:
- job: RichCodeNavUpload
  displayName: Rich Code Navigation Upload to Staging
  pool: Hosted Windows 2019 with VS2019
  steps:
  - template: install-dependencies.yml
  - script: dotnet build --no-restore -c $(BuildConfiguration) /v:m /bl:"$(Build.ArtifactStagingDirectory)/build_logs/build.binlog"
  - task: RichCodeNavIndexer@0
    displayName: RichCodeNav Upload
    inputs:
      languages: 'csharp'
      environment: staging
      isPrivateFeed: false
    continueOnError: true